name: Generate Architecture Diagram

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'docs/generate_architecture_diagram.py'
      - 'terraform/**'
      - 'docs/**'

jobs:
  generate-diagram:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Dependencies
      run: |
        pip install diagrams

    - name: Install GraphWiz
      uses: tlylt/install-graphviz@v1

    - name: Generate Diagram
      run: |
        python3 docs/generate_architecture_diagram.py

    - name: Commit and Push Diagram
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add docs/giglet-architecture.png || true
        git commit -m "Automated update: architecture diagram" || true
        git push